### ISSUE TITLE
README explanation

### ISSUE THREAD

**Issue by kavishdevar** [Gansgar/AAP-Protocol-Defintion#1]
Hey! First of all, great work!

What does this sentence mean? What exactly did Packetlogger parse the data as?
> Sadly Apple removed the parsing of the AAP language in systems above macOS Mojave (10.14)

(The PacketLogger on Sonoma does give out the raw data in the packets being sent and received over L2CAP)

**Comment by tyalie** [comment]
Yeah that was really imprecise. This was meant in regards to the PacketLogger application. Before macOS 10.14, this application had a definition for AAP packets, which it could use to display the packet semantics (the meaning of each bit and byte) to the end user. After 10.14, this was fully removed. Nowadays you can only see that it is an AAP packet, but not what every bit mean.

**Comment by kavishdevar** [comment]
Sad that we need newer versions of macos to use all the features of newer airpods.. Thanks!
